package edu.poly.entities;
// Generated Oct 19, 2019 11:11:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Carts generated by hbm2java
 */
@Entity
@Table(name="Carts"
    ,schema="dbo"
    ,catalog="java4"
)
public class Cart  implements java.io.Serializable {


     private int cartId;
     private Customer customers;
     private Date createdDate;
     private String status;
     private Set<CartDetail> cartDetailses = new HashSet<CartDetail>(0);

    public Cart() {
    }

	
    public Cart(int cartId, Customer customers) {
        this.cartId = cartId;
        this.customers = customers;
    }
    public Cart(int cartId, Customer customers, Date createdDate, String status, Set<CartDetail> cartDetailses) {
       this.cartId = cartId;
       this.customers = customers;
       this.createdDate = createdDate;
       this.status = status;
       this.cartDetailses = cartDetailses;
    }
   
     @Id 

    
    @Column(name="CartId", unique=true, nullable=false)
    public int getCartId() {
        return this.cartId;
    }
    
    public void setCartId(int cartId) {
        this.cartId = cartId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CustomerId", nullable=false)
    public Customer getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customer customers) {
        this.customers = customers;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CreatedDate", length=10)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Status")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="carts")
    public Set<CartDetail> getCartDetailses() {
        return this.cartDetailses;
    }
    
    public void setCartDetailses(Set<CartDetail> cartDetailses) {
        this.cartDetailses = cartDetailses;
    }




}


