package edu.poly.entities;
// Generated Oct 19, 2019 11:11:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="Products"
    ,schema="dbo"
    ,catalog="java4"
)
public class Product  implements java.io.Serializable {


     private int productId;
     private Category categories;
     private String name;
     private String image;
     private Integer quantity;
     private double price;
     private Date manufacturedDate;
     private String status;
     private String description;
     private Set<CartDetail> cartDetailses = new HashSet<CartDetail>(0);

    public Product() {
    }

	
    public Product(int productId, Category categories, String name, double price, Date manufacturedDate) {
        this.productId = productId;
        this.categories = categories;
        this.name = name;
        this.price = price;
        this.manufacturedDate = manufacturedDate;
    }
    public Product(int productId, Category categories, String name, String image, Integer quantity, double price, Date manufacturedDate, String status, String description, Set<CartDetail> cartDetailses) {
       this.productId = productId;
       this.categories = categories;
       this.name = name;
       this.image = image;
       this.quantity = quantity;
       this.price = price;
       this.manufacturedDate = manufacturedDate;
       this.status = status;
       this.description = description;
       this.cartDetailses = cartDetailses;
    }
   
     @Id 

   // @GeneratedValue(strategy = GenerationType.IDENTITY) //cho id tự tăng
    @Column(name="ProductId", unique=true, nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CategoryId", nullable=false)
    public Category getCategories() {
        return this.categories;
    }
    
    public void setCategories(Category categories) {
        this.categories = categories;
    }

    
    @Column(name="Name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="image")
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="Quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="Price", nullable=false, precision=53, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="manufacturedDate", nullable=false, length=10)
    public Date getManufacturedDate() {
        return this.manufacturedDate;
    }
    
    public void setManufacturedDate(Date manufacturedDate) {
        this.manufacturedDate = manufacturedDate;
    }

    
    @Column(name="Status")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="Description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set<CartDetail> getCartDetailses() {
        return this.cartDetailses;
    }
    
    public void setCartDetailses(Set<CartDetail> cartDetailses) {
        this.cartDetailses = cartDetailses;
    }




}


